spring:
  datasource:
    url: jdbc:postgresql://${jobservice.database.host:localhost}:${jobservice.database.port:5432}/${jobservice.database.db:job_postgres}
    username: ${jobservice.database.username}
    password: ${jobservice.database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: ${AMQP_SERVER_HOST}
    username: ${AMQP_USER}
    password: ${AMQP_PASSWORD}
    listener:
      simple:
        concurrency: ${AMQP_SERVER_CONCURRENCY}
        max-concurrency: ${AMQP_SERVER_MAX_CONCURRENCY}
        prefetch: 1
    publisher-confirm-type: correlated

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      base-path: /status

verapdf:
  rabbitmq:
    queues:
      tasks-queue:
        name: ${AMQP_SERVER_SENDING_QUEUE_NAME}
        max-size: ${AMQP_SERVER_SENDING_QUEUE_MAX_SIZE}
      listening-queue:
        name: ${AMQP_SERVER_LISTENING_QUEUE_NAME}
        max-size: ${AMQP_SERVER_LISTENING_QUEUE_MAX_SIZE}

springdoc:
  api-docs:
    path: /jobs/docs
  swagger-ui:
    path: /jobs/swagger.html
    operations-sorter: method
